### ISSUE TITLE
Wooting Double Movement Error

### ISSUE THREAD

**Issue by dynobeats** [WootingKb/wooting-double-movement#21]
Everytime i try to download or start Wooting double movement i get this error: https://gyazo.com/10271442c5be3f969be0c6ec350a6979

I dont know whats caused it since wooting used to work but then out of nowhere it stopped working.

**Comment by simon-wh** [comment]
That's quite strange, maybe a reinstall of the ViGEmBus failed. 

Have you tried [downloading and installing it manually](https://github.com/ViGEm/ViGEmBus/releases/tag/setup-v1.17.333) or following [this troubleshooting guide](https://github.com/WootingKb/wooting-double-movement/wiki/Troubleshooting#-vigembus-failed-to-install---error-code-2503) relating to ViGEm install

**Comment by dynobeats** [comment]
Thanks so much, installing vigembus manually worked for me! thank you so
much!

Den sön 23 maj 2021 kl 21:54 skrev Simon W ***@***.***>:

**Comment by simon-wh** [comment]
Glad it's sorted :+1:
