### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by quickkeu** [WootingKb/wooting-double-movement#24]
Everything works fine but when i open Wooting-double-movement it shows this error and i dont know how to fix 
![Unbenannt](https://user-images.githubusercontent.com/85577678/121228239-cd48a980-c88c-11eb-8e04-8e5865bf0e46.PNG)

**Comment by PastaJ36** [comment]
Please try this fix: https://github.com/WootingKb/wooting-double-movement/wiki/Troubleshooting#-updated-to-v131-and-it-doesnt-work-anymore
