### ISSUE TITLE
W wird nicht erkannt? 

### ISSUE THREAD

**Issue by timmy86519** [WootingKb/wooting-double-movement#26]
Moin, ich habe das Problem, dass wenn ich W und A oder D gleichzeitig drücke ich nach einer kurzen Zeit nur nach Links oder Rechts Läufe, also als würde ich nur A/D drücken. W wird theoretisch nach kurzer Zeit nich mehr erkannt. 
Kann da wer helfen?

**Comment by PastaJ36** [comment]
Press `D`(sideways) and then `W`(forward) at the start of every match for Fortnite to recognize your input device

The Double Movement app emulates a gamepad Joystick to create their specific running directions from digital keys.
There's currently a initialization issue from Fortnite at the start of every match that ignores the Joystick values until both Joystick axes have passed their deadzone threshold.

If that still didn't solve the problem checkout the [Troubleshooting Page](https://github.com/WootingKb/wooting-double-movement/wiki/Troubleshooting) or reach out on [Discord](https://discord.gg/GUz7VbPnvs) in the `#fortnite-double-movement` channel for a Live chat.
