### ISSUE TITLE
when you load in  a new match you can not move

### ISSUE THREAD

**Issue by bxltics** [WootingKb/wooting-double-movement#27]
when i load into  a match on fortnite i am not able to move

**Comment by DarrenVs** [comment]
Press `D`(sideways) and then `W`(forward) at the start of every match for Fortnite to recognize your input device

The Double Movement app emulates a gamepad Joystick to create their specific running directions from digital keys.
There's currently a initialization issue from Fortnite at the start of every match that ignores the Joystick values until both Joystick axes have passed their deadzone threshold.

If that still didn't solve the problem checkout the [Troubleshooting Page](https://github.com/WootingKb/wooting-double-movement/wiki/Troubleshooting) or reach out on [Discord](https://discord.gg/GUz7VbPnvs) in the `#fortnite-double-movement` channel for a Live chat.
