### ISSUE TITLE
There are some big issues

### ISSUE THREAD

**Issue by 24HOURSS** [WootingKb/wooting-double-movement#28]
the issue is when I try to download it it says "nefarius virtual game pad emulation bus not being correctly installed" can any 1 plz halp me with this issue? thanks!
![image](https://user-images.githubusercontent.com/86176691/122661096-9e91d380-d1a8-11eb-86a8-837824b6a8bd.png)

**Comment by simon-wh** [comment]
Follow [these instructions](https://github.com/WootingKb/wooting-double-movement/wiki/Troubleshooting#-vigembus-failed-to-install---error-code-2503) to ensure ViGEmBus gets correctly installed
