### ISSUE TITLE
I cant walk when i have the WASD off on my keybinds.

### ISSUE THREAD

**Issue by BrakoBamBam** [WootingKb/wooting-double-movement#29]
And if have them on i have normal movement.

**Comment by calderoats** [comment]
Please see:
https://github.com/WootingKb/wooting-double-movement/wiki/Troubleshooting#-when-you-walk-its-regular-keyboard-movement-or-worse

**Comment by BrakoBamBam** [comment]
And if have them on i have normal movement.
