### ISSUE TITLE
How to download on windows 8.1

### ISSUE THREAD

**Issue by Luciferrrrrrrrrrr** [WootingKb/wooting-double-movement#32]
How to download on windows 8.1 
It really helps me alot

**Comment by simon-wh** [comment]
I think your best bet would be try following [the guide for installing on Windows 7](https://github.com/WootingKb/wooting-double-movement/wiki/Troubleshooting#-how-to-install-on-windows-7)

**Comment by Luciferrrrrrrrrrr** [comment]
It's working thx
