### ISSUE TITLE
Cannot move unless A pressed

### ISSUE THREAD

**Issue by Oapples** [WootingKb/wooting-double-movement#35]
At the start of the game or when WASD movement is enabled by Fortnite (jumped out of battlepass, vehicle, boat, etc.) W and other keys are disabled until A is pressed after which WASD results in movement again.

**Comment by DarrenVs** [comment]
This is a technical issue unrelated to the Double Movement app, Wooting cannot fix this.
You can make a Fortnite bug report [here](https://www.epicgames.com/help/en-US/fortnite-c75/technical-support-c118/how-do-i-submit-a-bug-report-in-fortnite-a3334) to gather some attention to this problem for the Fortnite developers. 

## The problem
The Double Movement app emulates a Gamepad Joystick to create their specific running directions from digital keys.
There's currently a initialization issue from Fortnite that ignores the Joystick values until both Joystick axes have passed their hardcoded deadzone threshold, _each time you spawn in_.
### Workaround
*After you spawn in (aka Deploy from the Battlebuss, Leave a Vehicle, etc..):*
Press `D`(sideways) and then `W`(forward) for Fortnite to initialize the values for your Joystick.
