### ISSUE TITLE
Double movement not working in windows 8.1

### ISSUE THREAD

**Issue by Luciferrrrrrrrrrr** [WootingKb/wooting-double-movement#37]
I tried windows 7 process it doesn't work.. Plzzz help

**Comment by Luciferrrrrrrrrrr** [comment]
It's working

**Comment by Vigoreet** [comment]
> It's working 

you can use the wooting software in w7?

**Comment by simon-wh** [comment]
> you can use the wooting software in w7?

See [here](https://github.com/WootingKb/wooting-double-movement/wiki/Troubleshooting#-how-to-install-on-windows-7) for instructions on installing in w7
