### ISSUE TITLE
Wooting 

### ISSUE THREAD

**Issue by Jackskon** [WootingKb/wooting-double-movement#39]
Everytime I go in my inventory on keyboard and mouse it gives me controller in put how do I fix that?

**Comment by DarrenVs** [comment]
This is a technical game issue unrelated to the Double Movement app, Wooting cannot fix this.
You can make a Fortnite bug report [here](https://www.epicgames.com/help/en-US/fortnite-c75/technical-support-c118/how-do-i-submit-a-bug-report-in-fortnite-a3334) to gather some attention to this problem for the Fortnite developers. 

## The problem
The Double Movement app emulates a Gamepad Joystick to create their specific running directions from digital keyboard keys.
This style of mouse + gamepad input is referred to as 'Mixed input'.

The setting `Lock Input Method as Mouse` is supposed to support 'Mixed input' devices by locking the input feedback to keyboard and mouse:
![image](https://user-images.githubusercontent.com/2780639/129726869-04fb64f0-9e39-48dc-9f4a-36639bebe4aa.png)
But Fortnite's integration of 'Mixed input' does not work in menus (such as the Inventory), causing the UI to flip between Controller and Mouse mode whenever you try to walk with a menu open.

### Workaround
The best thing you can do right now is avoid pressing the movement keys whenever you open the inventory. You may still use the Auto-Walk hotkey to work around this problem.
