### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by fhlp** [WootingKb/wooting-double-movement#41]
Some times have to press 2 or 3 times ''W'' to move foward, some times feels like im pressing ''W'' repeatly fast and looks stuttering

first a thought that was my kb and change the ''W'' switch but still happening

**Comment by PastaJ36** [comment]
Are you using a Wooting keyboard? If so please [email](mailto:social@wooting.io) us or go to our [discord](https://wooting.io/discord)
