### ISSUE TITLE
i don't get the Xbox 360 device 

### ISSUE THREAD

**Issue by Ronaldo4011** [WootingKb/wooting-double-movement#45]
![image](https://user-images.githubusercontent.com/96626486/147361062-4a7a6ecc-7eee-4725-83f2-753c6247d311.png)

**Comment by simon-wh** [comment]
This app does not emulate an Xbox 360 controller, it emulates a Dualshock 4 controller so you will most likely see a more generic gamepad entry rather than an Xbox 360 one
