### ISSUE TITLE
I have setupped double movement but it is not working 

### ISSUE THREAD

**Issue by Ankitfn** [WootingKb/wooting-double-movement#46]
is:issue is:open The double movement is not working even i have setupped it twice and i also dont have xbox peripherals and Key2xInput what do I do?
![image](https://user-images.githubusercontent.com/97664946/149297030-8e470507-b8f0-4d95-b882-817276fd4032.png)
![image](https://user-images.githubusercontent.com/97664946/149297069-97229d6d-7932-4e7c-89fb-21bfb7feeaac.png)

**Comment by PastaJ36** [comment]
Best to go on our [discord](https://wooting.io/discord) for support or checkout the [faq](https://github.com/WootingKb/wooting-double-movement/wiki/Troubleshooting)
