### ISSUE TITLE
Cannot move in wooting.

### ISSUE THREAD

**Issue by koazzywastaken** [WootingKb/wooting-double-movement#47]
i logged on this afternoon unable to move with the wooting software, it no longer makes the controller connection sound, ive tried everything in the troubleshoot but with no help, i can only moved when unfocused and is really annoying, ive checked for anyone other softwares like Keys2x and none of it is active so im very confused about it. - im not sure what to do, as it seems that keys2x makes the connection sound and works, however wooting still doesnt.

**Comment by PastaJ36** [comment]
Best to go on our [discord](https://wooting.io/discord) for support or checkout the [faq](https://github.com/WootingKb/wooting-double-movement/wiki/Troubleshooting)
