### ISSUE TITLE
Cant turbo build

### ISSUE THREAD

**Issue by Dorian11123e** [WootingKb/wooting-double-movement#51]
So came here from the website, and i tried to fix it,it doesent work..? I cant turbo build while i have double movement on..? So maybe i need some help...

**Comment by Dorian11123e** [comment]
![image](https://user-images.githubusercontent.com/100202877/155123011-bbc36cb5-b0c2-4c84-91ca-65d4cbced8fa.png)
and it shows this... what do i choose here..?

**Comment by PastaJ36** [comment]
Best to go on our [discord](https://wooting.io/discord) for support or checkout the [faq](https://github.com/WootingKb/wooting-double-movement/wiki/Troubleshooting)
