### ISSUE TITLE
I can help

### ISSUE THREAD

**Issue by F1shyX** [WootingKb/wooting-double-movement#57]
![image](https://user-images.githubusercontent.com/111528616/185458608-aa6d337a-c0cb-4c5b-85c7-0e71f8843a12.png)

**Comment by simon-wh** [comment]
That error indicates that `ViGEm bus` aka "Nefarius Virtual Gamepad Emulation Bus" isn't installed correctly. You should follow the troubleshooting steps [here](https://github.com/WootingKb/wooting-double-movement/wiki/Troubleshooting#-vigembus-failed-to-install---wooting-double-movement-error--error-code-2503)
